### ISSUE TITLE
Branch master in Chat-API

### ISSUE THREAD

**Issue by maikealame** [xaamin/whatsapi#12]
Hey, it's look like the composer need v3.2 tag in chat-api, from 19 feb. But, has some new updates mainly from axotl. When i change the 3.2 for master, get error after login:

FatalErrorException in MGP25.php line 304:
Call to undefined method WhatsProt::sendPresence()

In WhatsProt class this method does not exist anymore. When you had fix to latest version ? Thanks in advance.

**Comment by maikealame** [comment]
I just comment method online on connect in client line 380:

```
    public function connectAndLogin()
    {
        if(!$this->connected)
        {
            $this->connected = true;

            $this->whatsProt->connect();
            $this->whatsProt->loginWithPassword($this->password);
            $this->whatsProt->sendGetServerProperties();
            //$this->online();
        }
    }
```

it's now working in last version, apparently.

**Comment by xaamin** [comment]
The last released version of [mgp25/Chat-API](https://github.com/WHAnonymous/Chat-API) is 3.2.
Work with dev-master branch is hard to maintain because some of the contributor may add incompatible changes and broke the funcionality in this repository.
Later, I try open new branch to unstable version and up to date with [mgp25/Chat-API](https://github.com/WHAnonymous/Chat-API) repo. Is not a promise =).

**Comment by maikealame** [comment]
But you are totally right, and not advisable too. It's better if chat-api puts big changes in new versions constantly. They has changed the token to register since 3.2 and many other corrections with axotl.
